version: '3.8'

services:
  frontend:
    build:
      target: development
    command: npm run dev
    volumes:
      - ../frontend-new:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    ports:
      - "5173:5173"  # Vite dev server port

  web:
    build:
      target: development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../warehouse_quote_app:/app
      - ../logs:/app/logs
    environment:
      - DEBUG=1
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/warehouse_quotes
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=DEBUG
    ports:
      - "8000:8000"

  db:
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ../scripts/init-dev-db.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  prometheus:
    volumes:
      - ../config/monitoring/prometheus.dev.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_dev_data:/prometheus

  grafana:
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_dev_data:/var/lib/grafana
      - ../config/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ../config/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro

volumes:
  postgres_dev_data:
  redis_dev_data:
  prometheus_dev_data:
  grafana_dev_data:
